### PR TITLE
Add method for listing endpoints for a given subscription

### PR DESCRIPTION
**Pull request by mattcameron**
This api endpoint doesn't seem to be documented, but would be very handy for listing endpoint for a single subscription! :)

### CODE REVIEW

**Comment by igrabes** [comment]
Hey @mattcameron good catch! Thanks

**Comment by mattcameron** [comment]
@igrabes any chance we could release this to rubygems.org? (sorry, I probably should have bumped the version number)

**Comment by igrabes** [comment]
Yup, I will do it shortly! On Jan 10, 2023, at 5:22 PM, mattcameron ***@***.***> wrote:﻿
@igrabes any chance we could release this to rubygems.org? (sorry, I probably should have bumped the version number)

**Comment by mattcameron** [comment]
Thanks!

**Comment by igrabes** [comment]
@mattcameron I just pushed 0.5.0 to rubygems

**Pull request merged**
